window.DOTA_HEROES = [
  { slug: "antimage", cn: "敌法师", name: "Anti-Mage", aliases: ["AM", "敌法"] },
  { slug: "axe", cn: "斧王", name: "Axe", aliases: ["斧"] },
  { slug: "bane", cn: "祸乱之源", name: "Bane", aliases: ["痛苦之源"] },
  { slug: "bloodseeker", cn: "嗜血狂魔", name: "Bloodseeker", aliases: ["血魔"] },
  { slug: "crystal_maiden", cn: "水晶室女", name: "Crystal Maiden", aliases: ["冰女", "CM"] },
  { slug: "drow_ranger", cn: "卓尔游侠", name: "Drow Ranger", aliases: ["小黑"] },
  { slug: "earthshaker", cn: "撼地者", name: "Earthshaker", aliases: ["小牛", "ES"] },
  { slug: "juggernaut", cn: "主宰", name: "Juggernaut", aliases: ["剑圣", "Jugg"] },
  { slug: "mirana", cn: "米拉娜", name: "Mirana", aliases: ["白虎"] },
  { slug: "nevermore", cn: "影魔", name: "Shadow Fiend", aliases: ["SF"] },
  { slug: "morphling", cn: "变体精灵", name: "Morphling", aliases: ["水人"] },
  { slug: "phantom_lancer", cn: "幻影长矛手", name: "Phantom Lancer", aliases: ["猴子", "PL"] },
  { slug: "puck", cn: "帕克", name: "Puck", aliases: ["仙女龙"] },
  { slug: "pudge", cn: "帕吉", name: "Pudge", aliases: ["屠夫"] },
  { slug: "razor", cn: "剃刀", name: "Razor", aliases: ["电棍"] },
  { slug: "sand_king", cn: "沙王", name: "Sand King", aliases: ["SK"] },
  { slug: "storm_spirit", cn: "风暴之灵", name: "Storm Spirit", aliases: ["蓝猫"] },
  { slug: "sven", cn: "斯温", name: "Sven", aliases: ["流浪剑客"] },
  { slug: "tiny", cn: "小小", name: "Tiny", aliases: ["山岭巨人"] },
  { slug: "vengefulspirit", cn: "复仇之魂", name: "Vengeful Spirit", aliases: ["VS"] },
  { slug: "windrunner", cn: "风行者", name: "Windranger", aliases: ["风行", "WR"] },
  { slug: "zuus", cn: "宙斯", name: "Zeus", aliases: ["宙斯"] },
  { slug: "kunkka", cn: "昆卡", name: "Kunkka", aliases: ["船长"] },
  { slug: "lina", cn: "莉娜", name: "Lina", aliases: ["火女"] },
  { slug: "lion", cn: "莱恩", name: "Lion", aliases: ["恶魔巫师"] },
  { slug: "shadow_shaman", cn: "暗影萨满", name: "Shadow Shaman", aliases: ["小Y", "SS"] },
  { slug: "slardar", cn: "斯拉达", name: "Slardar", aliases: ["大鱼人"] },
  { slug: "tidehunter", cn: "潮汐猎人", name: "Tidehunter", aliases: ["潮汐"] },
  { slug: "witch_doctor", cn: "巫医", name: "Witch Doctor", aliases: ["WD"] },
  { slug: "lich", cn: "巫妖", name: "Lich", aliases: ["51"] },
  { slug: "riki", cn: "力丸", name: "Riki", aliases: ["隐刺"] },
  { slug: "enigma", cn: "谜团", name: "Enigma", aliases: ["谜团"] },
  { slug: "tinker", cn: "修补匠", name: "Tinker", aliases: ["TK"] },
  { slug: "sniper", cn: "狙击手", name: "Sniper", aliases: ["火枪"] },
  { slug: "necrolyte", cn: "瘟疫法师", name: "Necrophos", aliases: ["死灵法", "NEC"] },
  { slug: "warlock", cn: "术士", name: "Warlock", aliases: ["WL"] },
  { slug: "beastmaster", cn: "兽王", name: "Beastmaster", aliases: ["BM"] },
  { slug: "queenofpain", cn: "痛苦女王", name: "Queen of Pain", aliases: ["女王", "QOP"] },
  { slug: "venomancer", cn: "剧毒术士", name: "Venomancer", aliases: ["剧毒"] },
  { slug: "faceless_void", cn: "虚空假面", name: "Faceless Void", aliases: ["虚空", "FV"] },
  { slug: "skeleton_king", cn: "冥魂大帝", name: "Wraith King", aliases: ["骷髅王", "WK"] },
  { slug: "death_prophet", cn: "死亡先知", name: "Death Prophet", aliases: ["DP"] },
  { slug: "phantom_assassin", cn: "幻影刺客", name: "Phantom Assassin", aliases: ["PA"] },
  { slug: "pugna", cn: "帕格纳", name: "Pugna", aliases: ["骨法"] },
  { slug: "templar_assassin", cn: "圣堂刺客", name: "Templar Assassin", aliases: ["TA", "圣堂"] },
  { slug: "viper", cn: "冥界亚龙", name: "Viper", aliases: ["毒龙"] },
  { slug: "luna", cn: "露娜", name: "Luna", aliases: ["月骑"] },
  { slug: "dragon_knight", cn: "龙骑士", name: "Dragon Knight", aliases: ["龙骑", "DK"] },
  { slug: "dazzle", cn: "戴泽", name: "Dazzle", aliases: ["暗牧"] },
  { slug: "rattletrap", cn: "发条技师", name: "Clockwerk", aliases: ["发条"] },
  { slug: "leshrac", cn: "拉席克", name: "Leshrac", aliases: ["老鹿"] },
  { slug: "furion", cn: "先知", name: "Nature's Prophet", aliases: ["先知", "NP"] },
  { slug: "life_stealer", cn: "噬魂鬼", name: "Lifestealer", aliases: ["小狗"] },
  { slug: "dark_seer", cn: "黑暗贤者", name: "Dark Seer", aliases: ["DS"] },
  { slug: "clinkz", cn: "克林克兹", name: "Clinkz", aliases: ["骨弓"] },
  { slug: "omniknight", cn: "全能骑士", name: "Omniknight", aliases: ["全能"] },
  { slug: "enchantress", cn: "魅惑魔女", name: "Enchantress", aliases: ["小鹿"] },
  { slug: "huskar", cn: "哈斯卡", name: "Huskar", aliases: ["神灵"] },
  { slug: "night_stalker", cn: "暗夜魔王", name: "Night Stalker", aliases: ["夜魔"] },
  { slug: "broodmother", cn: "育母蜘蛛", name: "Broodmother", aliases: ["蜘蛛"] },
  { slug: "bounty_hunter", cn: "赏金猎人", name: "Bounty Hunter", aliases: ["赏金", "BH"] },
  { slug: "weaver", cn: "编织者", name: "Weaver", aliases: ["蚂蚁"] },
  { slug: "jakiro", cn: "杰奇洛", name: "Jakiro", aliases: ["双头龙"] },
  { slug: "batrider", cn: "蝙蝠骑士", name: "Batrider", aliases: ["蝙蝠"] },
  { slug: "chen", cn: "陈", name: "Chen", aliases: ["陈"] },
  { slug: "spectre", cn: "幽鬼", name: "Spectre", aliases: ["UG"] },
  { slug: "doom_bringer", cn: "末日使者", name: "Doom", aliases: ["末日"] },
  { slug: "ancient_apparition", cn: "远古冰魄", name: "Ancient Apparition", aliases: ["冰魂", "AA"] },
  { slug: "ursa", cn: "熊战士", name: "Ursa", aliases: ["拍拍熊"] },
  { slug: "spirit_breaker", cn: "裂魂人", name: "Spirit Breaker", aliases: ["白牛", "SB"] },
  { slug: "gyrocopter", cn: "矮人直升机", name: "Gyrocopter", aliases: ["飞机"] },
  { slug: "alchemist", cn: "炼金术士", name: "Alchemist", aliases: ["炼金"] },
  { slug: "invoker", cn: "祈求者", name: "Invoker", aliases: ["卡尔"] },
  { slug: "silencer", cn: "沉默术士", name: "Silencer", aliases: ["沉默"] },
  { slug: "obsidian_destroyer", cn: "殁境神蚀者", name: "Outworld Destroyer", aliases: ["黑鸟", "OD"] },
  { slug: "lycan", cn: "狼人", name: "Lycan", aliases: ["狼人"] },
  { slug: "brewmaster", cn: "酒仙", name: "Brewmaster", aliases: ["熊猫"] },
  { slug: "shadow_demon", cn: "暗影恶魔", name: "Shadow Demon", aliases: ["毒狗", "SD"] },
  { slug: "lone_druid", cn: "德鲁伊", name: "Lone Druid", aliases: ["熊德", "LD"] },
  { slug: "chaos_knight", cn: "混沌骑士", name: "Chaos Knight", aliases: ["混沌", "CK"] },
  { slug: "meepo", cn: "米波", name: "Meepo", aliases: ["地卜师"] },
  { slug: "treant", cn: "树精卫士", name: "Treant Protector", aliases: ["大树"] },
  { slug: "ogre_magi", cn: "食人魔魔法师", name: "Ogre Magi", aliases: ["蓝胖"] },
  { slug: "undying", cn: "不朽尸王", name: "Undying", aliases: ["尸王"] },
  { slug: "rubick", cn: "拉比克", name: "Rubick", aliases: ["拉比克"] },
  { slug: "disruptor", cn: "干扰者", name: "Disruptor", aliases: ["萨尔"] },
  { slug: "nyx_assassin", cn: "司夜刺客", name: "Nyx Assassin", aliases: ["小强", "NA"] },
  { slug: "naga_siren", cn: "娜迦海妖", name: "Naga Siren", aliases: ["小娜迦"] },
  { slug: "keeper_of_the_light", cn: "光之守卫", name: "Keeper of the Light", aliases: ["光法", "KOTL"] },
  { slug: "wisp", cn: "艾欧", name: "Io", aliases: ["小精灵", "IO"] },
  { slug: "visage", cn: "维萨吉", name: "Visage", aliases: ["死灵龙"] },
  { slug: "slark", cn: "斯拉克", name: "Slark", aliases: ["小鱼人"] },
  { slug: "medusa", cn: "美杜莎", name: "Medusa", aliases: ["一姐"] },
  { slug: "troll_warlord", cn: "巨魔战将", name: "Troll Warlord", aliases: ["巨魔"] },
  { slug: "centaur", cn: "半人马战行者", name: "Centaur Warrunner", aliases: ["人马"] },
  { slug: "magnataur", cn: "马格纳斯", name: "Magnus", aliases: ["猛犸"] },
  { slug: "shredder", cn: "伐木机", name: "Timbersaw", aliases: ["伐木机"] },
  { slug: "bristleback", cn: "钢背兽", name: "Bristleback", aliases: ["刚背"] },
  { slug: "tusk", cn: "巨牙海民", name: "Tusk", aliases: ["海民"] },
  { slug: "skywrath_mage", cn: "天怒法师", name: "Skywrath Mage", aliases: ["天怒"] },
  { slug: "abaddon", cn: "亚巴顿", name: "Abaddon", aliases: ["亚巴顿"] },
  { slug: "elder_titan", cn: "上古巨神", name: "Elder Titan", aliases: ["大牛", "ET"] },
  { slug: "legion_commander", cn: "军团指挥官", name: "Legion Commander", aliases: ["军团", "LC"] },
  { slug: "techies", cn: "工程师", name: "Techies", aliases: ["炸弹人"] },
  { slug: "ember_spirit", cn: "灰烬之灵", name: "Ember Spirit", aliases: ["火猫"] },
  { slug: "earth_spirit", cn: "大地之灵", name: "Earth Spirit", aliases: ["土猫"] },
  { slug: "abyssal_underlord", cn: "孽主", name: "Underlord", aliases: ["大屁股"] },
  { slug: "terrorblade", cn: "恐怖利刃", name: "Terrorblade", aliases: ["TB"] },
  { slug: "phoenix", cn: "凤凰", name: "Phoenix", aliases: ["凤凰"] },
  { slug: "oracle", cn: "神谕者", name: "Oracle", aliases: ["神谕"] },
  { slug: "winter_wyvern", cn: "寒冬飞龙", name: "Winter Wyvern", aliases: ["冰龙", "WW"] },
  { slug: "arc_warden", cn: "天穹守望者", name: "Arc Warden", aliases: ["电狗"] },
  { slug: "monkey_king", cn: "齐天大圣", name: "Monkey King", aliases: ["大圣", "MK"] },
  { slug: "dark_willow", cn: "邪影芳灵", name: "Dark Willow", aliases: ["小仙女"] },
  { slug: "pangolier", cn: "石鳞剑士", name: "Pangolier", aliases: ["滚滚"] },
  { slug: "grimstroke", cn: "天涯墨客", name: "Grimstroke", aliases: ["墨客"] },
  { slug: "hoodwink", cn: "森海飞霞", name: "Hoodwink", aliases: ["松鼠"] },
  { slug: "void_spirit", cn: "虚无之灵", name: "Void Spirit", aliases: ["紫猫"] },
  { slug: "snapfire", cn: "电炎绝手", name: "Snapfire", aliases: ["老奶奶"] },
  { slug: "mars", cn: "玛尔斯", name: "Mars", aliases: ["马尔斯"] },
  { slug: "dawnbreaker", cn: "破晓辰星", name: "Dawnbreaker", aliases: ["锤妹"] },
  { slug: "marci", cn: "玛西", name: "Marci", aliases: ["玛西"] },
  { slug: "primal_beast", cn: "兽", name: "Primal Beast", aliases: ["兽", "大牛头"] },
  { slug: "muerta", cn: "琼英碧灵", name: "Muerta", aliases: ["女枪"] },
  { slug: "ringmaster", cn: "百戏大王", name: "Ringmaster", aliases: ["马戏团"] },
  { slug: "kez", cn: "凯", name: "Kez", aliases: ["凯"] }
];
